-- 1st Normal form
    -- All rows must be unique
    -- All data must also be atomic and non divisible
    -- Row order must not convey any information
    -- Mutiple data types should not exist in on column
    -- All tables must have a primary key
    -- No repeated groups
 
-- 2nd normal form
    -- Deletion and update anomaly
    /* Partial dependency: Exery column in a table should depend 
        on every primary key in a multicolumnar primary key table */

-- 3rd normal form
    /* Transitive dependency: No column should depend on another 
        columns other than that of the primary key */
    
-- 4th normal form
    /* Multivalued dependency: No one to many relations 
    in more than one independent columns */


-- CREATE TABLE sales_records (
--     id SERIAL PRIMARY KEY,
--     sales_id INTEGER,
--     name VARCHAR (255),
--     email VARCHAR (255),
--     age INTEGER,
--     address VARCHAR (255),
--     country VARCHAR (255),
--     phone VARCHAR (255),
--     product VARCHAR (255),
--     quantity INTEGER,
--     status VARCHAR (255),
--     order_date DATE,
--     delivery_date DATE
-- );

-- CREATE TABLE sales_records1 (
--     sales_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
--     id INTEGER,
--     name VARCHAR (255),
--     email VARCHAR (255),
--     age INTEGER,
--     address VARCHAR (255),
--     country VARCHAR (255),
--     phone VARCHAR (255),
--     product VARCHAR (255),
--     quantity INTEGER,
--     status VARCHAR (255),
--     order_date DATE,
--     delivery_date DATE
-- );

-- CREATE TABLE sales_records1 (
--     sales_id INTEGER GENERATED BY DEFAULT PRIMARY KEY,
--     id INTEGER,
--     name VARCHAR (255),
--     email VARCHAR (255),
--     age INTEGER,
--     address VARCHAR (255),
--     country VARCHAR (255),
--     phone VARCHAR (255),
--     product VARCHAR (255),
--     quantity INTEGER,
--     status VARCHAR (255),
--     order_date DATE,
--     delivery_date DATE
-- );

-- CREATE TABLE sales_records (
--     sales_id INTEGER PRIMARY KEY,
--     id INTEGER,
--     name VARCHAR (255),
--     email VARCHAR (255),
--     age INTEGER,
--     address VARCHAR (255),
--     country VARCHAR (255),
--     phone VARCHAR (255),
--     product VARCHAR (255),
--     quantity INTEGER,
--     status VARCHAR (255),
--     order_date DATE,
--     delivery_date DATE
-- );

-- ALTER TABLE sales_records
-- ADD CONSTRAINT sr_id_pk 
-- PRIMARY KEY (id);

-- pg_dump -U username -d database_name -f backup_file.sql
-- psql -U username -f backup_file.sql 